# -*- coding: utf-8 -*-
"""packages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VNaWqpuSGhfKZWJRbOIQpz-TRhbaE1Ih
"""

import os
os.system('pip install plotly-geo')
