# -*- coding: utf-8 -*-
"""packages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VNaWqpuSGhfKZWJRbOIQpz-TRhbaE1Ih
"""

$ pip install plotly-geo

$ pip install shapely

$ pip install -U kaleido

$ pip install fastapi

$ pip install python-multipart

$ pip install uvicorn
