# -*- coding: utf-8 -*-
"""lejohn_finalproj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RJHmRc8WKjtYRmJtwO03HGCI2hVvL3z4
"""

import pandas as pd
cows_2022=pd.read_csv("gs://lejohn_finalproj/Ohio_Dairy_2022.csv",dtype={'State ANSI':object,'County ANSI':object})
cows_2023=pd.read_csv("gs://lejohn_finalproj/Ohio_Dairy_2023.csv",dtype={'State ANSI':object,'County ANSI':object})

cows_2022.dropna(subset='CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>',inplace=True)
cows_2023.dropna(subset='CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>',inplace=True)

cows_2022.drop(cows_2022.loc[cows_2022['CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>']==' (D)'].index,inplace=True)
cows_2023.drop(cows_2023.loc[cows_2023['CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>']==' (D)'].index,inplace=True)

cows_2022['CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>'].replace(',','',inplace=True,regex=True)
cows_2023['CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>'].replace(',','',inplace=True,regex=True)

cows_total=cows_2022.merge(cows_2023,on='County ANSI')

cows_total.rename(columns={"CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>_x":'Dairy_Cows_x'},inplace=True)
cows_total.rename(columns={"CATTLE, COWS, MILK - INVENTORY  -  <b>VALUE</b>_y":'Dairy_Cows_y'},inplace=True)
cows_total['FIPS']=cows_total['State ANSI_x']+cows_total['County ANSI']
cows_total.dropna(axis=0,subset='FIPS',inplace=True)
cows_total.to_csv('cows_total.csv')

import plotly.figure_factory as ff
from matplotlib import pyplot as plt
from plotly.subplots import make_subplots
import plotly.graph_objects as go

cows_total['Dairy_Cow_Diff']=(cows_total['Dairy_Cows_y'].astype(int)/cows_total['Dairy_Cows_x'].astype(int)-1)*100
fig1=ff.create_choropleth(fips=cows_total['FIPS']\
                           ,values=cows_total['Dairy_Cow_Diff'].astype(int),scope=['Ohio'],county_outline={'color': 'rgb(255,255,255)', 'width': 0.5},\
                          legend_title='Dairy Cow % Change YoY',title='Ohio Dairy Cows')
fig1.show()

fig1.write_image("Ohio.png")
