# -*- coding: utf-8 -*-
"""Query.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LSDiKifRblNb7MiGTcyPV6u1M6myLVUg
"""
import os
from google.cloud import bigquery


client = bigquery.Client('fa23-i535-lejohn-finalproj')

# Perform a query.
QUERY = (
    "\
    SELECT * FROM\
      (SELECT County_x, Year_x, sum(Dairy_Cows_x) as cows\
      FROM `fa23-i535-lejohn-finalproj.Ohio_Cows.Ohio_Cows`\
      WHERE County_x in ('MADISON','CLARK','UNION')\
      GROUP BY  County_x, Year_x\
      union all\
      SELECT County_y, Year_y, sum(Dairy_Cows_y) as cows\
      FROM `fa23-i535-lejohn-finalproj.Ohio_Cows.Ohio_Cows`\
      WHERE County_y in ('MADISON','CLARK','UNION')\
      GROUP BY  County_y, Year_y)\
    ")

query_job = client.query(QUERY,location='US')  # API request
rows = query_job.result()  # Waits for query to finish

df=query_job.to_dataframe()
df.to_excel('Query.xlsx')

os.system("!gsutil cp 'Query.xlsx' 'gs://lejohn_finalproj/'")

